# Generated by Django 6.0.5 on 2026-05-15 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.TextField(verbose_name='提出内容')),
                ('grade', models.CharField(max_length=2, verbose_name='評価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提出日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
        ),
    ]
