# Generated by Django 6.0.5 on 2026-05-15

from django.db import migrations, models


def copy_student_info(apps, schema_editor):
    Assignment = apps.get_model('main', 'Assignment')
    for assignment in Assignment.objects.select_related('user'):
        full_name = f"{assignment.user.first_name} {assignment.user.last_name}".strip()
        assignment.student_number = assignment.user.username
        assignment.student_name = assignment.user.first_name or full_name or assignment.user.username
        assignment.save(update_fields=['student_number', 'student_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='student_name',
            field=models.CharField(default='', max_length=150, verbose_name='名前'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='student_number',
            field=models.CharField(default='', max_length=150, verbose_name='学籍番号'),
            preserve_default=False,
        ),
        migrations.RunPython(copy_student_info, migrations.RunPython.noop),
    ]
